version: 2
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    working_directory: ~/repo
    environment:
      JVM_OPTS: '-Xmx3200m'
      TERM: dumb
    steps:
    - checkout
    - run: 'chmod +x gradlew'
    - run: './gradlew clean fatJar dependencyCheckAnalyze'
    - store_artifacts:
        path: build/libs/LogRequestsToSQLite.jar
        destination: LogRequestsToSQLite-NightBuild.jar
workflows:
  version: 2
  scheduled-night-build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
